### ISSUE TITLE
external_validation entropy calculations

### ISSUE THREAD

**Issue by rjrich** [mlampros/ClusterR#38] opened 2022-10-02 12:48 UTC
I am using the R package, ClusterR, and the functions in "external_validation" to calculate external validation measures of clusterings.

The values from this code agree with other R codes I have tried (such as mclustcomp and NMF) with the exception of the entropy (H).

For example, with the external_validation code, I get H = 1.263, but with NMF and mclustcomp, I get 3.546; I think that the latter two values are for joint Shannon entropy.

Could you please tell me which of the various entropies the external_validation code is calculating?

In addition, I would like to calculate the normalized entropy. If the entropy is "H", would the normalized entropy be H/log2(n), where n = the number of clusters and log2 is the log to the base 2?

Thank you.

**Comment by mlampros** [comment] 2022-10-02 18:01
@rjrich 
can you add a reproducible example? You can include the sample data and what you receive with 'ClusterR', 'NMF' and 'mclustcomp' because I see which packages you use but I'm not sure about the functions or parameter setting that you use.

Let me also add a few details regarding the entropy function that is used in the 'ClusterR' package. It is based on the entropy formula of [a scientific paper](https://watermark.silverchair.com/btm134.pdf?token=AQECAHi208BE49Ooan9kkhW_Ercy7Dm3ZL_9Cf3qfKAc485ysgAAAuEwggLdBgkqhkiG9w0BBwagggLOMIICygIBADCCAsMGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQM55IZL4ueL9-mBGTqAgEQgIIClD8iIDh90uXKpP0UYNQsc3K6EAsIEp8YXU9GvsTTiQgNryFtr4XSK78bqic2ldmnqAazv1KiBxzxRj4gdNhvqD_OY43S5ZTL0pHrN8NZTmsYuG8Qz2IIeWbr6x26SZHkd60c7TAPPQZ9xB-nFQa0VpOcHM9YiMONiNwnA2cEcv8rxaGle_BxC-5mbB1QKX1iIPmQ0TGOCAE1B6yXYO3QGEdSyNzqJ4JADDcy9sL4CgPWplGdtWotC_xSZW126Nh8FC-4Va2VhsLYwPZQTsxOEqdOuc49AYTYKui66dyKV_cABjzJh-ByUoH4g6dDuZR6aayDLLlAv9GtWeNmS6VvCs3yamdjFJ7qCe6aLqI91J8aNq1q1rF0SSiz8hoN4ndFnE3w2eCwir2bHH-5o4r1WoxVJjqTd9XdzXfkr4NZQE7NTjUvOCtPQyNIN3M-3owCw6ZEZ3ro9DR40k2lhIs8eqNDUaK7Ja-w-edwSZ0R8Tt64uBKev3Fcxj3woyFEoTLMt5G6mWOZzum8tnt_ZvCM2WWllOw7HbaIpv4fzcJ1Y0PXACy_f0L3VZLqZlI7fWDjyG8za4lEb0iMk4UXWFYn1jX5zOw3xo_mxE-GKOGpESm_yGkUDVL6KvkSDNh27ZCt46kurvJcmSW78M1cLxja5ybvGErWY9SC3AeZPhlJA_QAx6-3LLr9NtS-H1z556oXQbEK3-Dscyavc7nUJUXCN-E2ZVG_RJyjTrtoixPuueJIB4YRFhrtZhxmbolZf196VL59m9n_K_t7legz9jFzwtKml6REyGsEB5DN13jhfOGC027EHi5_AzHuUpVSzXtaEGl0KYZIBnKoCKMNiFwKM1oyp0LAhN5EDdAjZlcgcc-M8Ty6g) (page 1498). You can also view the code for entropy in the [clustering_functions.R](https://github.com/mlampros/ClusterR/blob/master/R/clustering_functions.R#L2064-L2069) file.
From a first  look it seems to me that the 'mclustcomp' R package uses the [joint entropy](https://github.com/kisungyou/mclustcomp/blob/master/R/mclustcomp.R#L40) which also appears [on wikipedia as a formula](https://en.wikipedia.org/wiki/Joint_entropy)

> In addition, I would like to calculate the normalized entropy. If the entropy is "H", would the normalized entropy be H/log2(n), where n = the number of clusters and log2 is the log to the base 2?

Normally github issues are meant for bugs in the code of a repository and for more general questions I would suggest Stackoverflow or similar. 
If you already implemented the code for a specific feature based on a reference feel free to open a pull request. I currently do not plan to add any further features to the 'ClusterR' package

**Comment by rjrich** [comment] 2022-10-03 13:05
@mlampros 
Here is a simplified data frame designed to yield maximum entropy:
` X        T1    T2    T3
  <chr> <dbl> <dbl> <dbl>
1 C1        1     1     1
2 C2        2     2     2
3 C3        1     1     1
4 C4        2     2     2`

Here are the entropy values obtained with three different programs:

ClusterR external_validation: 1.2303
NMF: 1.0000
mclustcomp: 3.5033

Note that the entropy formulas for ClusterR external_validation and NMF are the same, whereas the entropy formula for mclustcomp is for the joint entropy, as you have pointed out.

**Comment by mlampros** [comment] 2022-10-03 18:14
I used an example from the ClusterR package to compute the purity and entropy of for ClusterR and NMF,

```R


require(ClusterR)
require(NMF)

data(dietary_survey_IBS)
y_true = dietary_survey_IBS$class

dat = dietary_survey_IBS[, -ncol(dietary_survey_IBS)]
X = center_scale(dat)

km = KMeans_rcpp(X, clusters = 3, num_init = 5, max_iters = 100, initializer = 'kmeans++', seed = 1)
y_kmeans = km$clusters

# 2-dim table
table(y_true, y_kmeans)

# purity

pur_clr = external_validation(true_labels = y_true, clusters = y_kmeans, method = "purity")
pur_nmf = NMF::purity(x = as.factor(y_kmeans), y = as.factor(y_true))     # x = predictions, y = true labels

identical(pur_clr, pur_nmf)
# TRUE

# entropy

entr_clr = external_validation(true_labels = y_true, clusters = y_kmeans, method = "entropy")
entr_nmf = NMF::entropy(x = as.factor(y_kmeans), y = as.factor(y_true))

identical(entr_clr, entr_nmf)
# FALSE

```
the purity is the same as you mentioned but the entropy is not
Before I verify the code of the ClusterR-entropy formula, are you aware of any other R package that computes entropy for output clusters?

**Comment by mlampros** [comment] 2022-10-03 18:57
It seems there are many other R packages that compute entropy ("The smaller the entropy, the better the clustering performance"). Two of these R packages "netropy" and "DescTools" agree in their results. Thus, someone would expect for my "dietary_survey_IBS" example data that a cluster number of 2 would give almost perfect clusterings. So if we begin from 2 and move to 3 or 4 clusters we would expect that the "entropy" increases because there are fewer matches between the true class and the predicted clusters. For some reason the "NMF::entropy()" gives always a 0 values, thus I'll exclude it from the computation.,

```R
require(netropy)
require(DescTools)
require(ClusterR)
require(glue)

# data
data(dietary_survey_IBS)
y_true = dietary_survey_IBS$class

dat = dietary_survey_IBS[, -ncol(dietary_survey_IBS)]
X = ClusterR::center_scale(dat)

clusts = 2:4

for (i in clusts) {
  
  km = ClusterR::KMeans_rcpp(X, clusters = i, num_init = 5, max_iters = 100, initializer = 'kmeans++', seed = 1)
  y_kmeans = km$clusters
  
  # ClusterR
  entr_clr = external_validation(true_labels = y_true, clusters = y_kmeans, method = "entropy")
  
  # DescTools
  shan_entr = DescTools::Entropy(x = y_kmeans, y = y_true, base = 2)
  
  # netropy
  df = data.frame(preds = y_kmeans, true = y_true)
  biv_entr = netropy::entropy_bivar(dat = df)
  
  cat(glue::glue("ClusterR: {round(entr_clr, 4)}  DescTools: {round(shan_entr, 4)}   netropy:  {round(biv_entr[1,1], 4)}"), "\n")
}

# Num_clust: 2  ClusterR: 0  DescTools: 1  netropy:  1 
# Num_clust: 3  ClusterR: 0.484  DescTools: 1.484  netropy:  1.484 
# Num_clust: 4  ClusterR: 0.6997  DescTools: 1.6997  netropy:  1.7
``
By increasing the number of clusters the entropy increases as someone would expect, 
because there more mismatches.
The Entropy in 'ClusterR' begins from 0.0 (identical clustering) whereas for 'DescTools' and 'netropy' from 1.0

**Comment by rjrich** [comment] 2022-10-03 19:03
@mlampros 

There is an R package "c2c" that contains a function "overall_entropy" that computes the entropy from a matrix. I tried it on my toy data set and got an entropy value of exactly one (1). It appears from these results that ct2c and NMF are outputting a normalized entropy whose values are bounded by [0,1], which is actually what I am after.

**Comment by rjrich** [comment] 2022-10-03 19:38
@mlampros

I noticed that when I ran external_validation on my toy data that the "variation of information" was 4.8589, which was identical to the Entropy computed by "Desc_Tools". Moreover, external_validation gives exactly one (1) for the "normalized variation of information", which happens to be the value I would expect for my data for a normalized entropy.

**Comment by mlampros** [comment] 2022-10-04 03:36
I'm glad you verified your results. Feel free to close this issue if the code of the 'ClusterR' package works as expected.

**Comment by rjrich** [comment] 2022-10-04 12:30
@mlampros

I think that my previous post was confusing and unclear. What I was trying to say was that there were other parameters computed by your ClusterR package that were giving numbers that I would have expected for different types of entropy. The original problem still remains, which is that the entropy calculated by the ClusterR package is different from the entropy calculated by the other packages I have tried and different from my expectation of entropy values. However, my plan is to use all of the values computed by the ClusterR package except for the entropy and to use another package for the entropy. Therefore, I will close this issue. Thank you very much for creating the ClusterR package!

**Closed** 2022-10-04 12:30 UTC
Labels: triage
